version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    working_directory: ~/nestjs-google-pubsub-microservice
    executor: node/default
    steps:
      - checkout
      - run:
          name: Update NPM version
          command: 'sudo npm install -g npm@latest'
      - node/install-packages
      - run:
          name: Build
          command: npm run build
      - run:
          name: Unit tests
          command: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .

  integration_tests:
    working_directory: ~/nestjs-google-pubsub-microservice
    machine: true
    environment:
      PUBSUB_EMULATOR_HOST: localhost:8681
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Prepare nvm
          command: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Upgrade Node.js
          command: |
            nvm install v18
            node -v
            nvm alias default v18
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Prepare
          command: |
            docker-compose up -d
            sleep 10
      - run:
          name: List containers
          command: docker ps
      - run:
          name: e2e tests
          command: npm run test:e2e

workflows:
  build-and-test:
    jobs:
      - build
      - integration_tests:
          requires:
            - build
